language: java
script: 
 - gradle check
 - gradle build
deploy:
   - provider: releases
     api_key: $githubkey
     file: build/libs/TriggerReactor.jar
     skip_cleanup: true
     on:
       tags: true
       branch: 'master'
   - provider: releases
     api_key: $githubkey
     file: build/libs/TriggerReactor.jar
     skip_cleanup: true
     prerelease: true
     on:
       tags: true
       branch: 'development'
