language: java
jdk:
  - openjdk8
before_install:
  - chmod +x gradlew
script:
  - ./gradlew clean check
  - ./gradlew build
deploy:
  - provider: releases
    api_key: $githubkey
    file_glob: true
    file:
      - build/libs/TriggerReactor-bukkit-latest-*.jar
      - build/libs/TriggerReactor-bukkit-legacy-*.jar
      - build/libs/TriggerReactor-sponge-*.jar
    skip_cleanup: true
    on:
      tags: true
      branch: 'master'
  - provider: releases
    api_key: $githubkey
    file_glob: true
    file:
      - build/libs/TriggerReactor-bukkit-latest-*.jar
      - build/libs/TriggerReactor-bukkit-legacy-*.jar
      - build/libs/TriggerReactor-sponge-*.jar
    skip_cleanup: true
    prerelease: true
    on:
      tags: true
      branch: 'development'
