# This snippet is public-domain, taken from
# https://github.com/PaperMC/Paper/blob/f9473d9928a922101bf5a1816c93e70a24bc7240/.github/workflows/close_invalid_prs.yml
name: Close invalid PRs

on:
  pull_request_target:
    types: [ opened ]

jobs:
  run:
    if: ${{ github.repository != github.event.pull_request.head.repo.full_name && github.head_ref == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "Please do not open pull requests from the `master` branch, create a new branch instead."