name: Java CI

on:
  push:
    tags: 
      - '*-Release'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Show status
      run: |
        echo event=${{ github.event_name }}
        echo action=${{ github.event.action }}
        echo ref=${{ github.ref }}
        echo merge=${{ github.event.pull_request.merged }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build javadoc
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/libs/TriggerReactor-*.jar
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
    - name: Update javadocs
      uses: cpina/github-action-push-to-another-repository@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      with:
        source-directory: 'build/docs/javadoc'
        destination-github-username: 'TriggerReactor'
        destination-repository-name: 'TriggerReactor.github.io'
        user-email: wysohn2002@naver.com
