name: Java CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Show status
      run: |
        echo event=${{ github.event_name }}
        echo action=${{ github.event.action }}
        echo tags=${{ contains(github.ref, 'tags') }}
        echo merge=${{ github.event.pull_request.merged }}
        echo result=${{ contains(github.ref, 'tags') || github.event.pull_request.merged == true }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      if: ${{ contains(github.ref, 'tags') || github.event.pull_request.merged == true }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/libs/TriggerReactor-*.jar
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
