on:
  push:
    branches:
    - master
    
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync development branch with master

    steps:
    - name: Checkout Dev
      uses: actions/checkout@v2
      with:
        ref: development
        
    - name: Merge master -> development
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: development
        target_branch: staging
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Timestamp
      run: date
