name: Java CI

on: ['push']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Show status
      run: |
        echo event=${{ github.event_name }}
        echo action=${{ github.event.action }}
        echo ref=${{ github.ref }}
        echo merge=${{ github.event.pull_request.merged }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew javadoc
    - name: check
      run: |
        ls build
        ls build/docs
        ls build/docs/javadoc
    - name: Update javadocs
      uses: cpina/github-action-push-to-another-repository@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      with:
        source-directory: 'build/docs/javadoc'
        destination-github-username: 'TriggerReactor'
        destination-repository-name: 'TriggerReactor.github.io'
        user-email: wysohn2002@naver.com
